### ISSUE TITLE
is there any way wherein bulk insert errors can be caught by external application?

### ISSUE THREAD

**Issue by Guilemon** [CatTheMagician/pillar#14]
for example, a value with incorrect type is being added to a clickhouse column, we get 500 error from clickhouse and entire bulk insert gets rejected /lost. is there any way this 500 error can be caught in application so a retry logic can be added?

**Comment by sofakingworld** [comment]
I guess there are 2 ways:
1. Adding retry logic with rejecting bad values (so clickhouse error need be parsed) and retry insert
2. Add more validations before inserts

Way 2 can be combined with Ecto Schemas:
In out projects we validate struct |> transform_to_map(with reject __struct__ field) |> insert

**Comment by Guilemon** [comment]
I tried adding validation as suggested. It works fine for our use case
Will be closing this
