### ISSUE TITLE
Better support for LowCardinality type conversion

### ISSUE THREAD

**Issue by jzlosman** [CatTheMagician/pillar#9]
It looks like there is limited support for `LowCardinality` columns, specifically for `LowCardinality(String)`.  Any other type, `UInt16`, `Float`, etc) fails to convert. 

However, there is full support for `Nullable(X)`.  It seems like that solution, modified for `LowCardinality` would solve this issue.

```
  def convert("Nullable" <> type, value) do
    case is_nil(value) do
      true -> nil
      false -> convert(type, value)
    end
  end
```

Possible solution would be:

```
  def convert("LowCardinality" <> type, value) do
    case is_nil(value) do
      true -> nil
      false -> convert(type, value)
    end
  end
```

**Comment by sofakingworld** [comment]
Yes, it seems to be true. I would be glad to get PR (preferably with a couple of tests for LowCardinality UInt16 and Float ). 

New release will be right after merge
